# Generated by Django 2.0.3 on 2019-10-29 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signuprecord', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='partyname',
            old_name='title',
            new_name='name',
        ),
    ]
