# Generated by Django 2.0.3 on 2019-11-20 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signuprecord', '0003_partyname_telephone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partyname',
            name='telephone',
            field=models.CharField(max_length=11, verbose_name='手机号码'),
        ),
    ]
